---
task:
    name: 'Cargo Test'
    freebsd_instance:
        matrix:
            image: 'freebsd-12-0-release-amd64'
            image: 'freebsd-11-2-release-amd64'
    install_script: |
        pkg install -y curl
        curl https://sh.rustup.sh -sSf \
            | sh -s -- -y
        . ${HOME}/.cargo/env
    before_cache_script: |
        rm -rf ${CARGO_HOME}/registry/index
    cargo_cache:
        folder: ${CARGO_HOME}/registry
    test_script: |
        env PATH="${HOME}/.cargo/bin:${PATH}" \
            cargo test

test:
    name: 'Cargo Test'
    test_script: 'cargo test'
