---
task:
    name: 'Cargo Test'
    freebsd_instance:
        matrix:
            image: 'freebsd-12-0-release-amd64'
            image: 'freebsd-11-2-release-amd64'
    env:
        CARGO_HOME: '${HOME}/.cargo'
        CIRRUS_SHELL: '/bin/sh'
    pkg_prepare_script: |
        pkg_repos_dir="/usr/local/etc/pkg/repos"
        mkdir -p "${pkg_repos_dir}"
        cat > "${pkg_repos_dir}/FreeBSD.conf" <<'EOF'
        FreeBSD: {
            url: "pkg+http://pkg.freebsd.org/${ABI}/latest"
        }
        EOF
    install_script: |
        pkg install -y \
            curl \
            rust
    before_cache_script: |
        rm -rf ${CARGO_HOME}/registry/index
    cargo_cache:
        folder: ${CARGO_HOME}/registry
    test_script: |
        . ${CARGO_HOME}/env
        cargo test
