[package]
name = "jail_exporter"
version = "0.2.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]

[dependencies]
clap = "2.31"
env_logger = "0.5"
hyper = "0.12"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
prometheus = "0.4"
sysctl = "0.2"
jail = "0.0.4"
