[package]
name = "jail_exporter"
version = "0.9.0"
description = "Prometheus exporter for FreeBSD jails."
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
authors = [
    "David O'Rourke <david.orourke@gmail.com>",
]
keywords = [
    "exporter",
    "freebsd",
    "jail",
    "metrics",
    "prometheus",
]

[dependencies]
askama = "0.7"
env_logger = "0.6"
failure = "0.1"
jail = "0.0.6"
log = "0.4"
prometheus = "0.5"
rctl = "0.0.5"

[dependencies.actix-web]
version = "0.7"
default-features = false

[dependencies.clap]
version = "2.32"
default-features = false
features = ["vec_map"]

[dependencies.users]
version = "0.8"
default-features = false

# Used by build.rs
[build-dependencies]
askama = "0.7"

# Used by cargo test
[dev-dependencies]
indoc = "0.3"
lazy_static = "1.2"
