[package]
name = "jail_exporter"
version = "0.9.0"
description = "Prometheus exporter for FreeBSD jails."
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
authors = [
    "David O'Rourke <david.orourke@gmail.com>",
]
keywords = [
    "exporter",
    "freebsd",
    "jail",
    "metrics",
    "prometheus",
]

[dependencies]
askama = "0.7"
clap = "2.32"
env_logger = "0.6"
jail = "0.0.6"
log = "0.4"
prometheus = "0.4"
rctl = "0.0.5"

[dependencies.actix-web]
version = "0.7"
default-features = false

[build-dependencies]
askama = "0.7"

[dev-dependencies]
lazy_static = "1.2"
