[package]
name = "jail_exporter"
version = "0.7.1"
edition = "2018"
authors = [
    "David O'Rourke <david.orourke@gmail.com>",
]

[dependencies]
clap = "2.32"
env_logger = "0.5"
jail = "0.0.5"
lazy_static = "1.1"
log = "0.4"
prometheus = "0.4"
rctl = "0.0.2"
warp = "0.1"
